### ISSUE TITLE
Audio Player

### ISSUE THREAD

**Issue by HidenoriMatsubayashi** [sony/flutter-elinux-plugins#3]
Create AudioPlayer plugin

**Comment by Taha-Firoz** [comment]
@HidenoriMatsubayashi okay so I've completed some very rough bindings for now and called it [Ping](https://github.com/Taha-Firoz/ping) because it's meant to only play simple sounds for notifications etc., not really meant to be a whole audio player. My only question is that the code should be the same for Windows or even Linux due to minaudio but since it's restricted to the elinux directory what am I supposed to do? Right now the only way for me to test it is to run it on an embedded flutter device. The example it broken I'll update it after I've done some testing and fixed up any bugs.

**Comment by Taha-Firoz** [comment]
Okay so I'm having trouble compiling the project with cmake, for some reason the linker can't find the `miniaudio.h` file 
```
/usr/bin/ld: ../plugins/ping/libping_plugin.so: undefined reference to `ma_data_source_set_looping'
/usr/bin/ld: ../plugins/ping/libping_plugin.so: undefined reference to `ma_device_get_state'
/usr/bin/ld: ../plugins/ping/libping_plugin.so: undefined reference to `ma_decoder_init_file'
/usr/bin/ld: ../plugins/ping/libping_plugin.so: undefined reference to `ma_device_init'
/usr/bin/ld: ../plugins/ping/libping_plugin.so: undefined reference to `ma_device_config_init'
/usr/bin/ld: ../plugins/ping/libping_plugin.so: undefined reference to `ma_decoder_read_pcm_frames'
/usr/bin/ld: ../plugins/ping/libping_plugin.so: undefined reference to `ma_device_uninit'
/usr/bin/ld: ../plugins/ping/libping_plugin.so: undefined reference to `ma_device_set_master_volume'
/usr/bin/ld: ../plugins/ping/libping_plugin.so: undefined reference to `ma_device_start'
/usr/bin/ld: ../plugins/ping/libping_plugin.so: undefined reference to `ma_device_stop'
/usr/bin/ld: ../plugins/ping/libping_plugin.so: undefined reference to `ma_device_get_master_volume'
/usr/bin/ld: ../plugins/ping/libping_plugin.so: undefined reference to `ma_decoder_uninit'
```
I was getting intellisense the whole time I was working so my path's are correct in the actual C file but I don't remember having to link header files too. Also I'm unable to compile with `-lpthread -lm -ldl` 😭😭😭 I followed the guides as best as I could but CMake is annoying. Could you have a look at my cmake file for Ping

**Comment by Taha-Firoz** [comment]
Do you know any I'm having this issue, I've added a fPIC flag into the plugins CMake, the plugin compiles fine on x86 but cross compiling gives this error.

```
'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
           /usr/bin/aarch64-linux-gnu-ld:
.../ubuntu18-arm64-sysroot/usr/lib/aarch64-linux-gnu/libm.a(s_sin.o):
           relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `__stack_chk_guard@@GLIBC_2.17' which may bind externally can not be used when making a
shared
           object; recompile with -fPIC
```

**Comment by makotosato-at** [comment]
Hello.

I tried porting audioplayers for elinux.
https://github.com/makotosato-at/flutter-elinux-plugins/tree/add_audioplayers/packages/audioplayers
It seems to be working fine in my environment(i.MX8MP board and RPi4).

**Comment by HidenoriMatsubayashi** [comment]
Great! If you send the pull request, I'll review it and then submit it.

**Comment by HidenoriMatsubayashi** [comment]
Closing. Thanks a lot.
