### ISSUE TITLE
Video Player use

### ISSUE THREAD

**Issue by suyulin** [sony/flutter-elinux-plugins#41]
hi, i run video/sample on pi,
![image](https://user-images.githubusercontent.com/6275411/136740749-e1f1508b-65b2-4a53-a731-e11766c10168.png)
![image](https://user-images.githubusercontent.com/6275411/136740787-707418d7-b61f-468c-93ed-9866b74e556e.png)
![image](https://user-images.githubusercontent.com/6275411/136740800-07b4836d-6a83-4149-9cfa-e84f7f72a300.png)

**Comment by HidenoriMatsubayashi** [comment]
Did you install [the required libraries](https://github.com/sony/flutter-elinux-plugins/tree/main/packages/video_player#required-libraries)?

**Comment by suyulin** [comment]
> Did you install [the required libraries](https://github.com/sony/flutter-elinux-plugins/tree/main/packages/video_player#required-libraries)?

 libraries install ok , gstreamer is work.
I try this  `gst-launch-1.0 videotestsrc ! videoconvert ! autovideosink` [https://qengineering.eu/install-gstreamer-1.18-on-raspberry-pi-4.html](url)
 
![image](https://user-images.githubusercontent.com/6275411/136760064-71cd040a-4911-4b38-9d7a-48ad878e4bdd.png)

**Comment by suyulin** [comment]
I try this cmd ```     cmake -DUSER_PROJECT_PATH=examples/flutter-video-player-plugin -DCMAKE_BUILD_TYPE=Release ..``` ,  it works.

**Comment by suyulin** [comment]
Video Player is only suppory wayland backend, not suppot gbm backend ?

**Comment by HidenoriMatsubayashi** [comment]
> Video Player is only suppory wayland backend, not suppot gbm backend ?

No, the video player plugin doesn't depend on display backends. Could you check whether the plugin .so files are linked correctly using `ldd` command? And could you share the whole log message?

**Comment by HidenoriMatsubayashi** [comment]
Thanks. But I couldn't reproduce your error. I don't know the cause at this time. What kind of OS are you using on RPI (3 or 4?) ?

**Comment by suyulin** [comment]
> As I mentioned, the video player plugin doesn't depend on display backends. It just uses GStreamer internally. Then, the textures created by GStreamer are composited in Flutter's side. Could you try out the following command on GBM backend?
> 
> ```
> $ gst-launch-1.0 -v playbin uri=<path to your video file>
> ```

```
 gst-launch-1.0 -v playbin uri=file:///home/pi/mixpad-elves-flutter/mixpad_x/assets/videos/home_edit.mp4
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
/GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0: ring-buffer-max-size = 0
/GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0: buffer-size = -1
/GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0: buffer-duration = -1
/GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0: use-buffering = false
/GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0: download = false
/GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0: uri = file:///home/pi/mixpad-elves-flutter/mixpad_x/assets/videos/home_edit.mp4
/GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0: connection-speed = 0
/GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0: source = "\(GstFileSrc\)\ source"
/GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0/GstTypeFindElement:typefind.GstPad:src: caps = video/quicktime, variant=(string)iso
/GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0/GstTypeFindElement:typefind.GstPad:src: caps = NULL
/GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0/GstMultiQueue:multiqueue0.GstPad:src_0: caps = video/x-h264, stream-format=(string)avc, alignment=(string)au, level=(string)3.1, profile=(string)high, codec_data=(buffer)0164001fffe1001a6764001facd301343be7921000000300100000030320f183138001000568eae043cb, width=(int)1220, height=(int)458, framerate=(fraction)25/1, pixel-aspect-ratio=(fraction)1/1
```

**Comment by suyulin** [comment]
> Did it work fine?

yes, it work fine.

**Comment by suyulin** [comment]
I found this.
```
cmake -DUSER_PROJECT_PATH=examples/flutter-video-player-plugin -DCMAKE_BUILD_TYPE=Release ..
compile to  libvideo_player_plugin.so
```
video_player/example  compile to libvideo_player_elinux_plugin.so . libvideo_player_elinux_plugin.so is not used.
I use  libvideo_player_plugin.so ,it work fine. 
if i use  libvideo_player_elinux_plugin.so 
```
./flutter_client_video: error while loading shared libraries: libvideo_player_plugin.so: cannot open shared object file: No such file or directory
cp libvideo_player_elinux_plugin.so  libvideo_player_plugin.so
./flutter_client_video: symbol lookup error: ./flutter_client_video: undefined symbol: VideoPlayerPluginRegisterWithRegistrar
```

**Comment by HidenoriMatsubayashi** [comment]
I'm not sure your environment, but if you use plugins in [`flutter-elinux-plugins`](https://github.com/sony/flutter-elinux-plugins), you need to use [`flutter-elinux`](https://github.com/sony/flutter-elinux). Please use [`flutter-elinux`](https://github.com/sony/flutter-elinux) to build and run your flutter apps.

**Comment by suyulin** [comment]
hi HidenoriMatsubayashi ,
I got it。I use https://github.com/sony/flutter-embedded-linux build flutter-client ，flutter-elinux-plugins/video/examples build bundle。
cmd run  flutter-client -b bundle. 
It will never run successfully。Because the libvideo_player_elinux_plugin.so is not linked to the flutter-client.
What are the solutions？Looking forward to your reply。

**Comment by Allan-Nava** [comment]
How do you fix?
