### ISSUE TITLE
Video Player Memory leak

### ISSUE THREAD

**Issue by suyulin** [sony/flutter-elinux-plugins#44]
hi,
I found video player have memory leak.
Test devices:
M1 mac mini : ubuntu 20.04 arm64
`➜  example git:(main) flutter-elinux doctor -v
[✓] Flutter (Channel unknown, 2.5.2, on Ubuntu 20.04.2 LTS 5.4.0-90-generic, locale en_US.UTF-8)
    • Flutter version 2.5.2 at /home/parallels/work/flutter-elinux/flutter
    • Upstream repository unknown
    • Framework revision 3595343e20 (9 weeks ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3
    • Flutter download mirror https://storage.flutter-io.cn

[✓] eLinux toolchain - develop for embedded Linux devices
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.22.0
    • pkg-config version 0.29.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.22.0
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✗] Flutter IDE Support (No supported IDEs installed)
    • IntelliJ - https://www.jetbrains.com/idea/
    • Android Studio - https://developer.android.com/studio/
    • VS Code - https://code.visualstudio.com/

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (3 available)
    • Linux (desktop)  • linux          • linux-arm64    • Ubuntu 20.04.2 LTS 5.4.0-90-generic
    • eLinux (desktop) • elinux-wayland • flutter-tester • Ubuntu 20.04.2 LTS 5.4.0-90-generic`
flutter-elinux run --profile
![image](https://user-images.githubusercontent.com/6275411/144696260-1b6cc819-f0fe-4197-bea1-f0c57ffac7e9.png)

**Comment by suyulin** [comment]
if stop play video , the memory is normal.
![image](https://user-images.githubusercontent.com/6275411/144699406-c2230e5e-d1c5-4958-b4b9-133fba823ef6.png)

**Comment by interestinghua** [comment]
hi do you solve this problem ?
