### ISSUE TITLE
I run demo application video_player has error:[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(216)] Could not make the context current to acquire the frame.

### ISSUE THREAD

**Issue by liujuan1018** [sony/flutter-elinux-plugins#58]
copied the same code: https://github.com/sony/flutter-elinux-plugins/blob/main/packages/video_player/example/lib/main.dart in flutter project. 
$ sudo apt install libglib2.0-dev
$ sudo apt install libgstreamer1.0-dev
build steps as below:
$flutter-elinux create .
$flutter-elinux build elinux --target-arch=arm64 --target-compiler-triple=aarch64-buildroot-linux-gnu --target-sysroot=aarch64-buildroot-linux-gnu/sysroot --target-compiler-flags=--gcc-toolchain=host --no-sound-null-safety

copy build\elinux\arm64\release\bundle to /test2/bundle_elinux_video on arm linux development boardrun .

root@rk3326_64:/test2/bundle_elinux_video# ./gstreamer_demo -b ./
arm_release_ver of this libmali is 'g2p0-01eac0', rk_so_ver is '7'.
Date: 2022-10-18 UTC
[07:11:37.516] libwayland: error in client communication (pid 1061)
[14819.717064] rk_vcodec: vpu_service_ioctl:2147: error: unknown vpu service ioctl cmd 40086c01
[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(216)] Could not make the context current to acquire the frame.
[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(216)] Could not make the context current to acquire the frame.
[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(216)] Could not make the context current to acquire the frame.
[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(216)] Could not make the context current to acquire the frame.
[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(216)] Could not make the context current to acquire the frame.
[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(216)] Could not make the context current to acquire the frame.
[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(216)] Could not make the context current to acquire the frame.
[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(216)] Could not make the context current to acquire the frame.
[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(216)] Could not make the context current to acquire the frame.
[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(216)] Could not make the context current to acquire the frame.
[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(216)] Could not make the context current to acquire the frame.
[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(216)] Could not make the context current to acquire the frame.
[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(216)] Could not make the context current to acquire the frame.
[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(216)] Could not make the context current to acquire the frame.
[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(216)] Could not make the context current to acquire the frame.
[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(216)] Could not make the context current to acquire the frame.
[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(216)] Could not make the context current to acquire the frame.
[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(216)] Could not make the context current to acquire the frame.
[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(216)] Could not make the context current to acquire the frame.
[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(216)] Could not make the context current to acquire the frame.
[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(216)] Could not make the context current to acquire the frame.
[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(216)] Could not make the context current to acquire the frame.
[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(216)] Could not make the context current to acquire the frame.
[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(216)] Could not make the context current to acquire the frame.
[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(216)] Could not make the context current to acquire the frame.
[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(216)] Could not make the context current to acquire the frame.
[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(216)] Could not make the context current to acquire the frame.
[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(216)] Could not make the context current to acquire the frame.
[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(216)] Could not make the context current to acquire the frame.
[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(216)] Could not make the context current to acquire the frame.
[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(216)] Could not make the context current to acquire the frame.
xdg_surface@18: error 3: xdg_surface has never been configured
[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(97)] Could not make the context current to destroy the GrDirectContext resources.

**Comment by HidenoriMatsubayashi** [comment]
I'm not sure, but can you please confirm that sample flutter app (no additional plugins) works fine on your device?

**Comment by HidenoriMatsubayashi** [comment]
I'll close this as no response.
