### ISSUE TITLE
Using media-kit

### ISSUE THREAD

**Issue by barribarrier** [sony/flutter-elinux-plugins#70]
Anyone had luck integrating [media-kit](https://github.com/media-kit/media-kit) with elinux for video playback?
media-kit uses libmpv under the hood on Linux.

**Comment by HidenoriMatsubayashi** [comment]
Looks like no.

**Comment by HidenoriMatsubayashi** [comment]
I'll close this ticket as we don't plan to add a video player plugin using media-kit. Thanks.
