### ISSUE TITLE
MissingPluginException encountered while try to start video recording

### ISSUE THREAD

**Issue by Arka2009** [sony/flutter-elinux-plugins#85]
Hi 

I am trying to use the camera plugins on the following configuration

1. amd64 Ubuntu 22.04 linux
2. flutter-elinux: 3.13.2 
3. camera: 0.10.5+5
4. camera_elinux: https://github.com/sony/flutter-elinux-plugins.git (main branch)
5. Display: X11

When I invoke the camera controller startVideoCapturing, I get the following exception
```
MissingPluginException(No implementation found for method startVideoRecording on channel plugins.flutter.io/camera)
```
Thanks

**Comment by HidenoriMatsubayashi** [comment]
> camera: 0.10.5+5

This version has not supported yet in flutter-elinux's camera plugin. See https://github.com/sony/flutter-elinux-plugins/blob/main/packages/camera/example/pubspec.yaml#L10

**Comment by HidenoriMatsubayashi** [comment]
And also, startVideoRecording has not supported yet too. See https://github.com/sony/flutter-elinux-plugins/issues/6

**Comment by HidenoriMatsubayashi** [comment]
Closing. Thanks.
