### ISSUE TITLE
[Video Player] Unhandled Exception: PlatformException

### ISSUE THREAD

**Issue by imaceda** [sony/flutter-elinux-plugins#88]
Hi, 

I'm trying to use the video-player plugin in flutter-elinux-plugins.
When running the example  on the my  ubuntu desktop, it completely works ok.

But when I cross compile this and run  video-player-plugin example on an arm64 embedded linux environment  
I encountered the error below during initialization.

Do I need a video player inside my embedded linux environment to be able to run this?
I'm running this over weston using flutter-client.

$> flutter-client --bundle=pathOfBundle  -f

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
#0      ELinuxVideoPlayerApi.initialize (package:video_player_elinux/src/messages.g.dart:202)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
#0      ELinuxVideoPlayerApi.setMixWithOthers (package:video_player_elinux/src/messages.g.dart:454)
<asynchronous suspension>
#1      VideoPlayerController.initialize (package:video_player/video_player.dart:434)
<asynchronous suspension>

**Comment by HidenoriMatsubayashi** [comment]
Okay, thanks. I just wanted to confirm if this issue depends on cross-building. I'm not sure what platform you are using, but please check https://github.com/sony/flutter-elinux-plugins/tree/main/packages/video_player#customize-for-your-target-devices first.

**Comment by imaceda** [comment]
I got it running.

I was lacking the actual flutter-embededded-linux - video-player-plugin,  and use it to run my flutter-linux-plugin(video-player).
I was initially just using the "flutter-wayland-client" to run the flutter-linux-plugin(video-player) app.

Thanks.

**Comment by HidenoriMatsubayashi** [comment]
Closing.
